src/main/java/com/example/demo/dto/AdviceDTO.java
package com.example.demo.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class AdviceDTO {

    private String message;

}

src/main/java/com/example/demo/dto/AuthorDTO.java
package com.example.demo.dto;

import com.example.demo.controller.BookController;
import com.example.demo.model.Author;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.ResourceSupport;

import java.util.Date;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;

public class AuthorDTO extends ResourceSupport {

    private Author author;

    public AuthorDTO(Author author, Link selfLink) {
        this.author = author;
        add(selfLink);
        add(linkTo(methodOn(BookController.class).getBooksByAuthorID(author.getId())).withRel("bookSet"));
    }

    public int getAuthorId() {
        return author.getId();
    }

    public String getAuthorName() {
        return author.getAuthorName();
    }

    public String getGender() {
        return author.getGender();
    }

    public Date getBirthDate() {
        return author.getBorn();
    }
}

src/main/java/com/example/demo/dto/BookDTO.java
package com.example.demo.dto;

import com.example.demo.controller.AuthorController;
import com.example.demo.model.Book;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.ResourceSupport;

import java.util.Date;

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo;
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;

public class BookDTO extends ResourceSupport {

    private Book book;

    public BookDTO(Book book, Link link) {
        this.book = book;
        add(link);
        add(linkTo(methodOn(AuthorController.class).getAuthorsByBookID(book.getId())).withRel("authorSet"));
    }

    public int getBookId() {
        return book.getId();
    }

    public String getBookName() {
        return book.getBookName();
    }

    public String getGenre() {
        return book.getGenre();
    }

    public Date getPublishingDate() {
        return book.getPublished();
    }

    public int getRating() {
        return book.getRating();
    }

}

src/main/java/com/example/demo/model/Author.java
package com.example.demo.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "author_id")
    private int id;
    @Column(name = "author_name")
    private String authorName;
    private String gender;
    @JsonIgnoreProperties(value = "authorSet")
    @ManyToMany
    @JoinTable(name = "author_book",
            joinColumns = @JoinColumn(name = "author_id", referencedColumnName = "author_id", nullable = false),
            inverseJoinColumns = @JoinColumn(name = "book_id", referencedColumnName = "book_id", nullable = false))
    private Set<Book> bookSet = new HashSet<>();

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Column(name = "birth")
    private Date born;

    @Override
    public String toString() {
        return "Author{" +
                "id=" + id +
                ", authorName='" + authorName + '\'' +
                ", gender='" + gender + '\'' +
                ", born=" + born +
                '}';
    }
}

src/main/java/com/example/demo/controller/advice/AdviceController.java
package com.example.demo.controller.advice;

import com.example.demo.dto.AdviceDTO;
import com.example.demo.exceptions.NoSuchAuthorException;
import com.example.demo.exceptions.NoSuchBookException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

@ControllerAdvice
public class AdviceController {

    @ExceptionHandler(NoSuchAuthorException.class)
    public ResponseEntity<AdviceDTO> noSuchAuthorExceptionAdvice() {
        return new ResponseEntity<>(new AdviceDTO("No specified author found."), HttpStatus.NOT_FOUND);
    }

    @ExceptionHandler(NoSuchBookException.class)
    public ResponseEntity<AdviceDTO> noSuchBookExceptionAdvice() {
        return new ResponseEntity<>(new AdviceDTO("No specified book found."), HttpStatus.NOT_FOUND);
    }
}

src/main/webapp/WEB-INF/jsp/BootstrapDependecies.jsp
<spring:url value="https://code.jquery.com/jquery-3.2.1.slim.min.js" var="jquery"/>
<spring:url value="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" var="popper"/>
<spring:url value="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" var="bootstrap"/>

<body>
<script src="${jquery}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="${popper}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="${bootstrap}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

src/main/webapp/WEB-INF/jsp/Navbar.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="BootstrapDependecies.jsp"%>

<nav class="navbar navbar-expand navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item" id="authorsPage">
                <a class="nav-link" href="/authors">Authors <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item" id="booksPage">
                <a class="nav-link" href="/books">Books</a>
            </li>
            <li class="btn-group">
                <a class="nav-link dropdown-toggle" href="#" onclick="cl()" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Tasks
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" id="drop">
                    <div>
                    <a class="dropdown-item" href="${pageContext.request.contextPath}/task/view/older">showAuthorsOlderParamAndSortByBorn</a>
                    </div>
                    <a class="dropdown-item" href="${pageContext.request.contextPath}/task/view/books">booksWhoseAuthorHasMoreThan1WrittenBooks</a>
                    <a class="dropdown-item" href="${pageContext.request.contextPath}/task/view/mostbooks">authorWhichHasMostBooks</a>
                    <a class="dropdown-item" href="${pageContext.request.contextPath}/task/view/genres">byGenres</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

<script>
    function cl() {
        $('#drop').dropdown('toggle');
    }
    // $('#navbarDropdown').on('click', function (event) {
    //     $('#drop').dropdown('toggle');
    // })

    $("a[class='dropdown-item']").on('click', function (event) {
        window.location.replace(this.getAttribute('href'));
        console.log(this);
    });
</script>

src/main/webapp/WEB-INF/jsp/TaskView.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="spr" uri="http://www.springframework.org/tags/form" %>
<html>
<%@include file="BootstrapDependecies.jsp"%>
<%@include file="Navbar.jsp"%>
<head>
    <title>Task</title>
    <h3>${message}</h3>
</head>
<body>
    <div class="table-responsive">
        <div class="m-2">
            <c:choose>
                <c:when test="${not empty authorList}">
                    <div>
                        <table class="table table-bordered table-hover">
                            <thead class="thead-light">
                            <th>Author ID</th>
                            <th>Author Name</th>
                            <th>Gender</th>
                            <th>Date of birth</th>
                            <th>Books</th>
                            <th></th>
                            </thead>
                            <tbody class="table-striped">
                            <c:forEach items="${authorList}" var="list">
                                <tr>
                                    <td>${list.id}</td>
                                    <td>${list.authorName}</td>
                                    <td>${list.gender}</td>
                                    <td>${list.born}</td>
                                    <td>${list.bookCount}</td>
                                </tr>
                            </c:forEach>
                            </tbody>
                        </table>
                    </div>
                </c:when>
                <c:when test="${not empty bookList}">
                    <div>
                        <table class="table table-bordered table-hover">
                            <thead class="thead-light">
                            <th>Book ID</th>
                            <th>Book Name</th>
                            <th>Publish Date</th>
                            <th>Genre</th>
                            <th>Book rating /10</th>
                            <th>Authors</th>
                            <th></th>
                            </thead>
                            <tbody class="table-striped">
                            <c:forEach items="${bookList}" var="books">
                                <tr>
                                    <td>${books.id}</td>
                                    <td>${books.bookName}</td>
                                    <td>${books.published}</td>
                                    <td>${books.genre}</td>
                                    <td>${books.rating}</td>
                                    <td>${books.authorCount}</td>
                                </tr>
                            </c:forEach>
                            </tbody>
                        </table>
                    </div>
                </c:when>
                <c:otherwise>
                    <div>
                        <table class="table table-bordered table-hover">
                            <thead class="thead-light">
                            <th>Genre</th>
                            <th>Count</th>
                            </thead>
                            <tbody class="table-striped">
                            <c:forEach items="${genres}" var="genre">
                                <tr>
                                    <td>${genre.key}</td>
                                    <td>${genre.value}</td>
                                </tr>
                            </c:forEach>
                            </tbody>
                        </table>
                    </div>
                </c:otherwise>
            </c:choose>
        </div>
    </div>
    <c:if test="${not empty sortable}">
        <div>
            <%--<form method="get">--%>
                <label>Age:</label>
                <input type="text" id="ageInput" placeholder="Natural number" value="55">
                <a class="btn btn-primary" onclick="getFunction({num : 1})">Ascending</a>
                <a class="btn btn-primary" onclick="getFunction({num : 2})">Descending</a>
            <%--</form>--%>
        </div>
    </c:if>
</body>
</html>

<script>
    function getFunction(parameters) {
        var num = parameters.num;
        var age = $('#ageInput').val();
        if(!isNaturalNumber(age)) return;
        if(num === 1) {
            window.location.replace('/task/view/older?age=' + age);
        } else {
            window.location.replace('/task/view/older?age=' + age + '&desc=1');
        }

    }

    function isNaturalNumber(n) {
        n = n.toString(); // force the value incase it is not
        var n1 = Math.abs(n),
            n2 = parseInt(n, 10);
        return !isNaN(n1) && n2 === n1 && n1.toString() === n;
    }
</script>